from .mae_blue_cyan import *
from .mae_blue_magenta import *
from .mae_blue_yellow import *
from .mae_cyan_magenta import *
from .mae_cyan_yellow import *
from .mae_cyan import *
from .mae_green_cyan import *
from .mae_green_magenta import *
from .mae_green_yellow import *
from .mae_magenta_yellow import *
from .mae_magenta import *
from .mae_red_cyan import *
from .mae_red_magenta import *
from .mae_red_yellow import *
from .mae_yellow import *