
# --- Define which layers you want to use ---
layers_cfg = [
    
	{"type": "perlin", "frequency": 100.0, "octaves": 6},
	{"type": "perlin", "frequency": 10.0, "seed": 78},
    {"type": "flow_field", "seed": 15},
    {"type": "heightmap_flow_spectrum", "seed": 822},
    {"type": "blue_noise", "mode": "field", "seed": 572},
    {"type": "multi_scale_flow", "seed": 786},
    {"type": "procedural_curvature", "seed": 666},
    {"type": "gradient_edges", "seed": 720},
    {"type": "fractal"},
    {"type": "gaussian_noise", "seed": 99},
    {"type": "simplex_noise", "seed": 83, "scale": 5.0},
    {"type": "simplex_noise", "seed": 0, "scale": 100.0},
    {"type": "laplacian_gaussian"},
    {"type": "curl_noise_flow"},
    {"type": "voronoi_cells", "num_seeds": 50},
    {"type": "checkerboard_full_gray", "block_size": 1, "seed": 42},
    {"type": "fbm_noise", "seed": 42},
    {"type": "fbm_vein", "seed": 29},
    {"type": "fbm_rock", "seed": 1990},
    
	{"type": "perlin_flow", "freq": 0.1, "octaves": 10, "gain": 1.0},
    {"type": "bandpass", "cutoff": 0.009},#"cutoff": 0.01},
    
	{"type": "checkerboard_radial", "tiles_x": 15, "tiles_y": 23},
    {"type": "checkerboard_radial", "fade_mult": 1.1, "tiles_x": 50, "tiles_y": 39},
	{"type": "voronoi_segmentation", "num_seeds": 100},
	{"type": "grid", "spacing": 4, "thickness": 2},
	{"type": "checkerboard", "block_size": 4},
	{"type": "radial_gradient"},
	{"type": "linear_gradient", "direction": "horizontal"},
	{"type": "linear_gradient", "direction": "vertical"},

    #{"type": "perlin", "frequency": 100.0, "octaves": 6},
	#{"type": "flow_field", "seed": 15},
    #{"type": "heightmap_flow_spectrum", "seed": 822},
	#{"type": "multi_scale_flow", "seed": 786},
    #{"type": "procedural_curvature", "seed": 666},
    #{"type": "gaussian_noise", "seed": 99},
    #{"type": "simplex_noise", "seed": 83, "scale": 5.0},
	#{"type": "laplacian_gaussian"},
    #{"type": "curl_noise_flow"},
    #{"type": "voronoi_cells", "num_seeds": 50},
    #{"type": "checkerboard_full_gray", "block_size": 3, "seed": 42},
	#{"type": "perlin_flow"},
    #{"type": "checkerboard", "block_size": 17},
    
	#{"type": "linear_gradient"},
	#{"type": "linear_gradient", "orientation": "vertical"},
    #{"type": "grid"},


	#{"type": "perlin", "frequency": 10.0, "seed": 78},
	#{"type": "blue_noise", "mode": "field", "seed": 572},
    #{"type": "gradient_edges", "seed": 720},
    #{"type": "fractal"},
	#{"type": "simplex_noise", "seed": 0, "scale": 100.0},
	#{"type": "checkerboard_full_gray", "block_size": 7, "seed": 69},
    #{"type": "checkerboard_full_gray", "block_size": 11, "seed": 2},
    #{"type": "fbm_noise", "seed": 42},
    #{"type": "fbm_vein", "seed": 29},
    #{"type": "fbm_rock", "seed": 1990},
	#{"type": "bandpass", "cutoff": 0.009},
	#{"type": "checkerboard_radial", "fade_mult": 1.1, "tiles_x": 50, "tiles_y": 39},
    #{"type": "checkerboard_radial", "tiles_x": 15, "tiles_y": 23},    
    #{"type": "edge_like_flow"},
    
	#{"type": "radial_gradient"},
    #{"type": "bilinear_blend"},
    #{"type": "random_gradient_field"},
    #{"type": "voronoi_segmentation", "num_seeds": 150},
    #{"type": "checkerboard", "block_size": 24},
    #{"type": "checkerboard_full_gray", "block_size": 51, "seed": 748},
    #{"type": "checkerboard_full_gray", "block_size": 30, "seed": 533},
    #{"type": "checkerboard_alt_gray", "block_size": 4, "seed": 75},
    #{"type": "checkerboard_radial", "fade_mult": 1.0},
    #{"type": "triangle_pattern", "mode": "alt", "size": 32, "seed": 42},
    #{"type": "triangle_pattern", "mode": "rand", "size": 7},
    #{"type": "hexagon_pattern", "mode": "rand", "size": 8, "seed": 69},
    #{"type": "hexagon_pattern", "mode": "rand", "orientation": "flat", "size": 24},

]